apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: system-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0
        ports:
        - containerPort: 1883
        - containerPort: 9001
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: system-monitor
spec:
  selector:
    app: mosquitto
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  - name: websocket
    port: 9001
    targetPort: 9001
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: system-monitor
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
    log_type all
    
    listener 9001
    protocol websockets